on: push

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 缓存Rust依赖和构建产物
      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/
            ~/.cargo/git/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # 设置Rust工具链
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-pc-windows-msvc

      # 构建发布版
      - name: Build Release
        run: cargo build --release --target x86_64-pc-windows-msvc

      # 列出目标目录内容
      - name: List target directory
        run: dir D:\a\hello\

      # 上传构建产物
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: D:\a\hello\hello.exe
          if-no-files-found: warn
