on: push

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置Rust工具链
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-pc-windows-msvc

      # 构建发布版
      - name: Build Release
        run: cargo build --release --target x86_64-pc-windows-msvc

      # 上传构建产物
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: target/release/*.exe
          if-no-files-found: error
